docs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^inf/$', views.inf, name='inf'),
    url(r'^professor/$', views.professor, name='professor'),
    url(r'^geraDisplayDict/$', views.geraDisplayDict, name='geraDisplayDict'),
    url(r'^geraResp/$', views.geraResp, name='geraResp'),
]

lattes/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^docs/', include('docs.urls', namespace='docs')),
]

docs/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

docs/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.template.context_processors import csrf
from django.template.context_processors import request
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import lxml.html as lh
import json
import re
from listaProfes import *
from baixaLattes import *


def index(request):
    return render_pagina(request, 'docs.html', None)

@csrf_exempt 
def inf(request):
    c = geradict()
    return render_pagina(request, 'inf.html', c)

def render_pagina(request, destino, c):
    return render(request, destino, c)


@csrf_exempt 
def professor(request):
	cvPath = './docs/CVs/'
        request_body = json.loads(request.body)
	idLattes = request_body['id']
	cvPath += idLattes

	if os.path.exists(cvPath):
		arquivoH = open(cvPath)
		cvLattesHTML = arquivoH.read()
		
	else:
		cvLattesHTML = baixaCVLattes(idLattes)
		file = open(cvPath, 'w')
		file.write(cvLattesHTML)
		file.close()


	response = {}
	return HttpResponse(response, content_type="application/json")
@csrf_exempt 
def geraResp(request):
	cvPath = './docs/CVs/'
        request_body = json.loads(request.body)
	idLattes = request_body['id']
	cvPath += idLattes
	doc=lh.parse(cvPath)
	div=doc.xpath('./body/div/div/div/div/div/div/div/div[@id="artigos-completos"]')[0]
	artigos = (div.find_class('artigo-completo'))
	numArtigos = (len(artigos))
	i = 0
	artigosString = ''
	artigosString += '<div style="text-align:left"><font size="4">'
	while(i < numArtigos):
		div2=doc.xpath('./body/div/div/div/div/div/div/div/div/div[@class="artigo-completo"]')[i]
		for elem in div2:
			artigosString+= elem.text_content().replace('\n','') 
			
	
		artigosString+= '<br><a class="icone-producao icone-doi" href="' 
		try:artigosString+= elem.xpath('//a[contains(@href,"doi")]/@href')[i] 
		except: pass
		artigosString+= '" target="_blank">view</a>		'
		artigosString += '<br><br>'
		i+=1
	
	artigosString+='</font></div>'
	artigosString+='<a class="w3-btn-floating w3-hover-green" href=""><</a>'
	
	
	return HttpResponse(artigosString, content_type="application/json")

def geradict():
    c = {
	'DIC' : INF
    }
    return c


@csrf_exempt 
def geraDisplayDict(request):
    request_body = json.loads(request.body)
    string = request_body['string']

    dic = geradict()['DIC']
    dicPorKey = {k:v for k,v in dic.iteritems() if re.match(string, k, re.I)}	
    dicPorValue ={}
    for k in dic:
	for v in dic[k]:
	    if v == 'nome':
	        for word in dic[k][v].split(' '):
		    if re.match(string, word, re.I):
		        dicPorValue.update({k: dic[k]})
	    elif re.match(string, dic[k][v], re.I):
	        dicPorValue.update({k: dic[k]})
	    
		
    dicSearch = dict(dicPorKey.items() + dicPorValue.items())
    



    displayHtml = geraDisplayHTML(dicSearch)

    if not displayHtml:
	displayHtml = "Sem resultados para '"+string+"'."
	
	
	
    response = {
	'displayHtml': displayHtml,
    }
    return HttpResponse(displayHtml, content_type="application/json")


def geraDisplayHTML(dic):
	displayFinal = ''
	for key, value in dic.items():
		display = '<div class="w3-quarter w3-center w3-hover-opacity">'
		display+= '<a id="'
		display+= value['idLattes'] 
		display+= '" class="profe" onclick="profe(this);">'
		display+= '<img src="' + value['pic'] + '" style="height:200px" >'
		display+= '<h3>' +  key + '</h3>'
		display+= '<h5>' + value['nome'] + '</h5>'
		display+= '<p>' + value['idLattes'] + '</p>'
		display+= '</a></div>'
		displayFinal += display
	return displayFinal

docs/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style>

body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-sidenav a {padding:20px}
a {text-decoration: none}
#searchField { font-size: medium}
</style>

<script>
// Script to open and close sidenav
//document.getElementById("searchfield").onfocus = function() {myFunction()};

function hideLogo() {
    $("#searchLogo").hide();
}
function showLogo() {
    setTimeout(function () {
    	$("#searchLogo").show();    
    }, 200);
}

function w3_open() {	
    document.getElementById("mySidenav").style.display = "block";
}

function w3_close() {
    document.getElementById("mySidenav").style.display = "none";
}

function test(){
	
	var string = $('#searchField').val();

	$.ajax({
		type: "POST",
		url: "{% url "docs:geraDisplayDict" %}",
	        data: JSON.stringify({string:string}),
		success: function(response){
			$("#profes").html(response);
	        },
       	});


	
}
</script>

<body>

<!-- Sidenav (hidden by default) -->
<nav class="w3-sidenav w3-card-2 w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:25%;min-width:200px" id="mySidenav">
  <a href="javascript:void(0)" onclick="w3_close()" 
  class="w3-closenav">Close Menu</a>
  <a href="{% url "docs:index" %}">fpLattes</a></div>
  <a href="#about" onclick="w3_close()">About</a>
</nav> 

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge w3-padding-xlarge" style="max-width:1200px;margin:auto">
	<div class="w3-opennav w3-left w3-hover-text-grey" onclick="w3_open()">☰</div>	
	<div class="w3-right">
	<!--<form id="searchForm"> -->
		<input id="searchField" class="w3-input w3-animate-input w3-left" type="text"  onfocus="hideLogo()" onblur="showLogo()" style="width:50%" placeholder="pesquisa" onkeydown="test()" onkeyup="test()" >
				<i id="searchLogo" class="material-icons w3-large w3-center">search</i>
	<!--</form>-->
	</div>
	<div class="w3-center""><br> </div>	
  </div>
</div>

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

   {% block body_block %}{% endblock %}  

  <hr id="about">
  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>Guilherme Rodrigues e Tatiane Stivelman</h3>
    <h4>Prof. Manuel Menezes de Oliveira Neto</h3>
  </div>
  <hr>

</div>

</body>
</html>

docs/templates/docs.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="institutos">

    <div class="w3-third w3-center w3-hover-opacity">
     <a href="{% url "docs:inf" %}">
          <img src="{% static "images/inf.png" %}" style="width:100%">
          <h3>INF</h3>
          <p>Instituto de Informática</p>
     </a>
    </div>

   <div class="w3-third w3-center w3-hover-opacity">
     <a href="">
          <img src="{% static "images/ia.png" %}" style="width:100%">
          <h3>IA</h3>
          <p>Instituto de Artes</p>
     </a>
    </div>
    
    <div class="w3-third w3-center w3-hover-opacity">
     <a href="">
          <img src="{% static "images/if.png" %}" style="width:100%">
          <h3>IF</h3>
          <p>Instituto de Física</p>
     </a>
    </div>
 </div>
{% endblock %}

docs/templates/inf.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}

<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script>
function profe(el) {
	var id = el.id;
	$('#profes').hide();
	$('#loader').html('<img src="/static/images/infinity.gif" style="height:80px"><br><h5> Baixando CV</h5>');
	$.ajax({
		type: "POST",
		url: "{% url "docs:professor" %}",
	        contentType: 'application/json; charset=utf-8',
	        data: JSON.stringify({id:id}),
	        success: function(response){
			$('#profes').show();
			geraResp(id);
			$('#loader').html('');
	       },
	});
}

function geraResp(id){
	var id = id;
	$.ajax({
		type: "POST",
		url: "{% url "docs:geraResp" %}",
	        contentType: 'application/json; charset=utf-8',
	        data: JSON.stringify({id:id}),
	        success: function(response){
			$('#profes').html(response);
	       },
	});
}

</script>

<div class="w3-row-padding w3-padding-16 w3-center" id="profes">
{% for key, value in DIC.items %}
<div class="w3-quarter w3-center w3-hover-opacity">
     <a id="{{ value.idLattes }}" class='profe' onclick='profe(this);'>
          <img src="{{value.pic}}" style="height:200px" >
          <h3>{{ key }}</h3>
          <h5>{{ value.nome }}</h5>
	  <p> {{ value.idLattes }} </p>
     </a>
</div>
{% endfor %}
</div>

<div id='loader' class="w3-center">
</div>

<!-- Pagination 
<div class="w3-center w3-padding-32">
  <ul class="w3-pagination">
    <li><a class="w3-black" href="#">1</a></li>
    <li><a class="w3-hover-black" href="#">2</a></li>
    <li><a class="w3-hover-black" href="#">3</a></li>
    <li><a class="w3-hover-black" href="#">4</a></li>
    <li><a class="w3-hover-black" href="#">»</a></li>
  </ul>
</div>-->

{% endblock %} 